export enum CodeErrors {
  FAIL_TO_FIND_USER = 'FAIL_TO_FIND_USER',
  FAIL_TO_CREATE_USER = 'FAIL_TO_CREATE_USER',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  FAIL_TO_CREATE_ROLE = 'FAIL_TO_CREATE_ROLE',
}
