name: Homolog deploy

on:
  push:
    branches:
      - 'develop'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
            HOSTNAME : ${{ secrets.SSH_HOST  }}
            USER_NAME : ${{ secrets.SSH_USER  }}
            
        run: |
          ssh -i ${PRIVATE_KEY} ${USER_NAME}@${HOSTNAME} '
            whoami
          '
